name: cross compile dotnet app
on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
    build:
      runs-on: macos-14
      steps:

      - name: checkout
        uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x
      - name: build dotnet binaries
        run: make build
      - name: size of binaries
        run: make size
      - name: file info
        run: make file
  
    linux-static:
      runs-on: ubuntu-latest
      strategy:
        fail-fast: false
        matrix:
          platform: [amd64, arm64]
      steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        if: matrix.platform == 'arm64'
        with:
          platforms: arm64    
      - name: docker_build_linux_musl_${{ matrix.platform }}
        run: make docker_build_linux_musl_${{ matrix.platform }}
      - name: size of binaries
        run: du -sh ./bin/linux-musl-${{ matrix.platform }}/hello_dotnet
      - name: run
        run: ./bin/linux-musl-${{ matrix.platform }}/hello_dotnet
  