name: cross compile dotnet app
on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
    build:
      runs-on: macos-14
      steps:

      - name: checkout
        uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x
      - name: build dotnet binaries
        run: make build
      - name: size of binaries
        run: make size
      - name: file info
        run: make file
  
    linux-static:
      runs-on: ubuntu-latest
      steps:

      - name: checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64    
      - name: docker_build_linux_musl_amd64
        run: make docker_build_linux_musl_amd64
      - name: docker_build_linux_musl_arm64
        run: make docker_build_linux_musl_arm64
      - name: size of binaries
        run: make size
      - name: file info
        run: make file
  